const TRANSLATIONS = {
    en: {
        title: "AC Tonnage & Load Calculator",
        roomDimensions: "Room Dimensions",
        length: "Room Length",
        width: "Room Width",
        height: "Room Height",
        floor: "Floor Level",
        windows: "Windows & Doors",
        numWindows: "Number of Windows",
        numDoors: "Number of Doors",
        sunExposure: "Sun Exposure",
        roomDetails: "Room Details",
        insulation: "Insulation Type",
        occupants: "Number of Occupants",
        furniture: "Furniture Type",
        tempSettings: "Temperature Settings",
        targetTemp: "Target Temperature",
        usagePeriod: "Usage Period",
        calculate: "Calculate Load",
        results: "Calculation Results",
        currency: "USD",
        selectCountry: "Select Your Country",
        selectLanguage: "Select Language",
        energyUsageAndCosts: "Energy Usage & Costs",
        dailyUsage: "Daily Usage (24 hours)",
        energyUsage: "Energy Usage",
        estimatedCost: "Estimated Cost",
        basedOn: "Based on",
        sleepPeriod: "Sleep Period Usage",
        egyptianTierInfo: "Based on Egyptian tiered pricing",
        egyptianTiers: "Egyptian electricity tiers",
        tonnageRequired: "Required Tonnage",
        coolingCapacity: "Cooling Capacity",
        currentDraw: "Estimated Current Draw",
        perMinute: "Per minute",
        perHour: "Per hour",
        perDay: "Per day",
        btuLoad: "BTU Load",
        kilowattLoad: "Kilowatt Load",
        selectFloor: "Select Floor Level",
        groundFloor: "Ground Floor",
        middleFloor: "Middle Floor",
        topFloor: "Top Floor",
        noSun: "No Direct Sunlight",
        morningSun: "Morning Sun",
        afternoonSun: "Afternoon Sun",
        allDaySun: "All Day Sun",
        poorInsulation: "Poor Insulation",
        averageInsulation: "Average Insulation",
        goodInsulation: "Good Insulation",
        minimalFurniture: "Minimal Furniture",
        woodenFurniture: "Wooden Furniture",
        metalFurniture: "Metal Furniture",
        mixedFurniture: "Mixed Furniture",
        sleepTime: "Sleep Time (11:59 PM - 7:00 AM)",
        fullDay: "Full Day (24 Hours)"
    },
    ar: {
        title: "حاسبة حمل التكييف",
        roomDimensions: "أبعاد الغرفة",
        length: "طول الغرفة",
        width: "عرض الغرفة",
        height: "ارتفاع الغرفة",
        floor: "مستوى الطابق",
        windows: "النوافذ والأبواب",
        numWindows: "عدد النوافذ",
        numDoors: "عدد الأبواب",
        sunExposure: "التعرض للشمس",
        roomDetails: "تفاصيل الغرفة",
        insulation: "نوع العزل",
        occupants: "عدد الأشخاص",
        furniture: "نوع الأثاث",
        tempSettings: "إعدادات درجة الحرارة",
        targetTemp: "درجة الحرارة المطلوبة",
        usagePeriod: "فترة الاستخدام",
        calculate: "حساب الحمل",
        results: "نتائج الحساب",
        currency: "جنيه",
        selectCountry: "اختر بلدك",
        selectLanguage: "اختر اللغة",
        energyUsageAndCosts: "استهلاك الطاقة والتكاليف",
        dailyUsage: "الاستخدام اليومي (24 ساعة)",
        energyUsage: "استهلاك الطاقة",
        estimatedCost: "التكلفة المقدرة",
        basedOn: "على أساس",
        sleepPeriod: "استهلاك فترة النوم",
        egyptianTierInfo: "حسب التسعير المتدرج المصري",
        egyptianTiers: "شرائح الكهرباء المصرية",
        tonnageRequired: "الطنية المطلوبة",
        coolingCapacity: "قدرة التبريد",
        currentDraw: "السحب المقدر للتيار",
        perMinute: "في الدقيقة",
        perHour: "في الساعة",
        perDay: "في اليوم",
        btuLoad: "حمل BTU",
        kilowattLoad: "حمل الكيلوواط",
        selectFloor: "اختر مستوى الطابق",
        groundFloor: "الطابق الأرضي",
        middleFloor: "طابق متوسط",
        topFloor: "الطابق العلوي",
        noSun: "لا يوجد ضوء شمس مباشر",
        morningSun: "شمس الصباح",
        afternoonSun: "شمس بعد الظهر",
        allDaySun: "شمس طوال اليوم",
        poorInsulation: "عزل ضعيف",
        averageInsulation: "عزل متوسط",
        goodInsulation: "عزل جيد",
        minimalFurniture: "أثاث قليل",
        woodenFurniture: "أثاث خشبي",
        metalFurniture: "أثاث معدني",
        mixedFurniture: "أثاث مختلط",
        sleepTime: "وقت النوم (11:59 م - 7:00 ص)",
        fullDay: "يوم كامل (24 ساعة)"
    },
    es: {
        title: "Calculadora de Tonelaje y Carga de AC",
        roomDimensions: "Dimensiones de la Habitación",
        length: "Largo",
        width: "Ancho",
        height: "Altura",
        floor: "Nivel del Piso",
        windows: "Ventanas y Puertas",
        numWindows: "Número de Ventanas",
        numDoors: "Número de Puertas",
        sunExposure: "Exposición Solar",
        roomDetails: "Detalles de la Habitación",
        insulation: "Tipo de Aislamiento",
        occupants: "Número de Ocupantes",
        furniture: "Tipo de Mobiliario",
        tempSettings: "Ajustes de Temperatura",
        targetTemp: "Temperatura Objetivo",
        usagePeriod: "Período de Uso",
        calculate: "Calcular Carga",
        results: "Resultados del Cálculo",
        currency: "Peso",
        selectFloor: "Seleccionar Nivel del Piso",
        groundFloor: "Planta Baja",
        middleFloor: "Piso Medio",
        topFloor: "Último Piso",
        noSun: "Sin Luz Solar Directa",
        morningSun: "Sol de la Mañana",
        afternoonSun: "Sol de la Tarde",
        allDaySun: "Sol Todo el Día",
        poorInsulation: "Aislamiento Deficiente",
        averageInsulation: "Aislamiento Promedio",
        goodInsulation: "Buen Aislamiento",
        minimalFurniture: "Mobiliario Mínimo",
        woodenFurniture: "Mobiliario de Madera",
        metalFurniture: "Mobiliario de Metal",
        mixedFurniture: "Mobiliario Mixto",
        sleepTime: "Hora de Dormir (11:59 PM - 7:00 AM)",
        fullDay: "Día Completo (24 Horas)"
    },
    fr: {
        title: "Calculateur de Tonnage et Charge de Climatisation",
        roomDimensions: "Dimensions de la Pièce",
        length: "Longueur",
        width: "Largeur",
        height: "Hauteur",
        floor: "Niveau d'Étage",
        windows: "Fenêtres et Portes",
        numWindows: "Nombre de Fenêtres",
        numDoors: "Nombre de Portes",
        sunExposure: "Exposition au Soleil",
        roomDetails: "Détails de la Pièce",
        insulation: "Type d'Isolation",
        occupants: "Nombre d'Occupants",
        furniture: "Type de Mobilier",
        tempSettings: "Réglages de Température",
        targetTemp: "Température Cible",
        usagePeriod: "Période d'Utilisation",
        calculate: "Calculer la Charge",
        results: "Résultats du Calcul",
        currency: "Euro",
        selectFloor: "Sélectionner le Niveau d'Étage",
        groundFloor: "Rez-de-Chaussée",
        middleFloor: "Étage Intermédiaire",
        topFloor: "Dernier Étage",
        noSun: "Pas de Lumière Solaire Directe",
        morningSun: "Soleil du Matin",
        afternoonSun: "Soleil de l'Après-Midi",
        allDaySun: "Soleil Toute la Journée",
        poorInsulation: "Isolation Faible",
        averageInsulation: "Isolation Moyenne",
        goodInsulation: "Bonne Isolation",
        minimalFurniture: "Mobilier Minimal",
        woodenFurniture: "Mobilier en Bois",
        metalFurniture: "Mobilier en Métal",
        mixedFurniture: "Mobilier Mixte",
        sleepTime: "Heure de Sommeil (11:59 PM - 7:00 AM)",
        fullDay: "Journée Complète (24 Heures)"
    },
    de: {
        title: "Klimaanlagen Tonnage-Rechner",
        roomDimensions: "Raumabmessungen",
        length: "Länge",
        width: "Breite",
        height: "Höhe",
        floor: "Stockwerk",
        windows: "Fenster und Türen",
        numWindows: "Anzahl der Fenster",
        numDoors: "Anzahl der Türen",
        sunExposure: "Sonneneinstrahlung",
        roomDetails: "Raumdetails",
        insulation: "Isolierungstyp",
        occupants: "Anzahl der Personen",
        furniture: "Möbeltyp",
        tempSettings: "Temperatureinstellungen",
        targetTemp: "Zieltemperatur",
        usagePeriod: "Nutzungszeitraum",
        calculate: "Last Berechnen",
        results: "Berechnungsergebnisse",
        currency: "Euro",
        selectFloor: "Stockwerk Wählen",
        groundFloor: "Erdgeschoss",
        middleFloor: "Mittleres Stockwerk",
        topFloor: "Oberstes Stockwerk",
        noSun: "Keine Direkte Sonneneinstrahlung",
        morningSun: "Morgensonne",
        afternoonSun: "Nachmittagssonne",
        allDaySun: "Den Ganzen Tag Sonne",
        poorInsulation: "Schlechte Isolierung",
        averageInsulation: "Durchschnittliche Isolierung",
        goodInsulation: "Gute Isolierung",
        minimalFurniture: "Minimale Möbel",
        woodenFurniture: "Holzmöbel",
        metalFurniture: "Metallmöbel",
        mixedFurniture: "Gemischte Möbel",
        sleepTime: "Schlafenszeit (11:59 PM - 7:00 AM)",
        fullDay: "Ganzer Tag (24 Stunden)"
    },
    it: {
        title: "Calcolatore Tonnellaggio Condizionatore",
        roomDimensions: "Dimensioni Stanza",
        length: "Lunghezza",
        width: "Larghezza",
        height: "Altezza",
        floor: "Piano",
        windows: "Finestre e Porte",
        numWindows: "Numero di Finestre",
        numDoors: "Numero di Porte",
        sunExposure: "Esposizione Solare",
        roomDetails: "Dettagli Stanza",
        insulation: "Tipo di Isolamento",
        occupants: "Numero di Occupanti",
        furniture: "Tipo di Arredamento",
        tempSettings: "Impostazioni Temperatura",
        targetTemp: "Temperatura Obiettivo",
        usagePeriod: "Periodo di Utilizzo",
        calculate: "Calcola Carico",
        results: "Risultati Calcolo",
        currency: "Euro",
        selectFloor: "Seleziona Piano",
        groundFloor: "Piano Terra",
        middleFloor: "Piano Intermedio",
        topFloor: "Ultimo Piano",
        noSun: "Nessuna Luce Solare Diretta",
        morningSun: "Sole del Mattino",
        afternoonSun: "Sole del Pomeriggio",
        allDaySun: "Sole Tutto il Giorno",
        poorInsulation: "Isolamento Scarso",
        averageInsulation: "Isolamento Medio",
        goodInsulation: "Buon Isolamento",
        minimalFurniture: "Arredamento Minimo",
        woodenFurniture: "Arredamento in Legno",
        metalFurniture: "Arredamento in Metallo",
        mixedFurniture: "Arredamento Misto",
        sleepTime: "Orario di Sonno (11:59 PM - 7:00 AM)",
        fullDay: "Giornata Intera (24 Ore)"
    },
    ru: {
        title: "Калькулятор Мощности Кондиционера",
        roomDimensions: "Размеры Помещения",
        length: "Длина",
        width: "Ширина",
        height: "Высота",
        floor: "Этаж",
        windows: "Окна и Двери",
        numWindows: "Количество Окон",
        numDoors: "Количество Дверей",
        sunExposure: "Воздействие Солнца",
        roomDetails: "Детали Помещения",
        insulation: "Тип Изоляции",
        occupants: "Количество Людей",
        furniture: "Тип Мебели",
        tempSettings: "Настройки Температуры",
        targetTemp: "Целевая Температура",
        usagePeriod: "Период Использования",
        calculate: "Рассчитать Нагрузку",
        results: "Результаты Расчета",
        currency: "Рубль",
        selectFloor: "Выбрать Этаж",
        groundFloor: "Первый Этаж",
        middleFloor: "Средний Этаж",
        topFloor: "Верхний Этаж",
        noSun: "Нет Прямого Солнечного Света",
        morningSun: "Утреннее Солнце",
        afternoonSun: "Дневное Солнце",
        allDaySun: "Солнце Весь День",
        poorInsulation: "Плохая Изоляция",
        averageInsulation: "Средняя Изоляция",
        goodInsulation: "Хорошая Изоляция",
        minimalFurniture: "Минимальная Мебель",
        woodenFurniture: "Деревянная Мебель",
        metalFurniture: "Металлическая Мебель",
        mixedFurniture: "Смешанная Мебель",
        sleepTime: "Время Сна (11:59 PM - 7:00 AM)",
        fullDay: "Весь День (24 Часа)"
    },
    zh: {
        title: "空调负荷计算器",
        roomDimensions: "房间尺寸",
        length: "长度",
        width: "宽度",
        height: "高度",
        floor: "楼层",
        windows: "窗户和门",
        numWindows: "窗户数量",
        numDoors: "门的数量",
        sunExposure: "阳光照射",
        roomDetails: "房间细节",
        insulation: "隔热类型",
        occupants: "人数",
        furniture: "家具类型",
        tempSettings: "温度设置",
        targetTemp: "目标温度",
        usagePeriod: "使用时段",
        calculate: "计算负荷",
        results: "计算结果",
        currency: "元",
        selectFloor: "选择楼层",
        groundFloor: "一楼",
        middleFloor: "中间楼层",
        topFloor: "顶楼",
        noSun: "无阳光直射",
        morningSun: "早晨阳光",
        afternoonSun: "下午阳光",
        allDaySun: "全天阳光",
        poorInsulation: "隔热差",
        averageInsulation: "隔热一般",
        goodInsulation: "隔热好",
        minimalFurniture: "最少家具",
        woodenFurniture: "木制家具",
        metalFurniture: "金属家具",
        mixedFurniture: "混合家具",
        sleepTime: "睡眠时间 (11:59 PM - 7:00 AM)",
        fullDay: "全天 (24 小时)"
    },
    ja: {
        title: "エアコン容量計算機",
        roomDimensions: "部屋の寸法",
        length: "長さ",
        width: "幅",
        height: "高さ",
        floor: "階数",
        windows: "窓とドア",
        numWindows: "窓の数",
        numDoors: "ドアの数",
        sunExposure: "日照",
        roomDetails: "部屋の詳細",
        insulation: "断熱タイプ",
        occupants: "人数",
        furniture: "家具タイプ",
        tempSettings: "温度設定",
        targetTemp: "目標温度",
        usagePeriod: "使用期間",
        calculate: "負荷計算",
        results: "計算結果",
        currency: "円",
        selectFloor: "階数を選択",
        groundFloor: "1階",
        middleFloor: "中間階",
        topFloor: "最上階",
        noSun: "直射日光なし",
        morningSun: "朝の日差し",
        afternoonSun: "午後の日差し",
        allDaySun: "一日中の日差し",
        poorInsulation: "断熱が悪い",
        averageInsulation: "断熱が普通",
        goodInsulation: "断熱が良い",
        minimalFurniture: "最小限の家具",
        woodenFurniture: "木製家具",
        metalFurniture: "金属製家具",
        mixedFurniture: "混合家具",
        sleepTime: "睡眠時間 (11:59 PM - 7:00 AM)",
        fullDay: "一日中 (24時間)"
    },
    ko: {
        title: "에어컨 용량 계산기",
        roomDimensions: "방 크기",
        length: "길이",
        width: "너비",
        height: "높이",
        floor: "층",
        windows: "창문과 문",
        numWindows: "창문 수",
        numDoors: "문 수",
        sunExposure: "일조량",
        roomDetails: "방 세부사항",
        insulation: "단열 유형",
        occupants: "사용 인원",
        furniture: "가구 유형",
        tempSettings: "온도 설정",
        targetTemp: "목표 온도",
        usagePeriod: "사용 기간",
        calculate: "부하 계산",
        results: "계산 결과",
        currency: "원",
        selectFloor: "층 선택",
        groundFloor: "1층",
        middleFloor: "중간층",
        topFloor: "최상층",
        noSun: "직사광선 없음",
        morningSun: "아침 햇살",
        afternoonSun: "오후 햇살",
        allDaySun: "하루 종일 햇살",
        poorInsulation: "단열이 나쁨",
        averageInsulation: "단열이 보통",
        goodInsulation: "단열이 좋음",
        minimalFurniture: "최소한의 가구",
        woodenFurniture: "나무 가구",
        metalFurniture: "금속 가구",
        mixedFurniture: "혼합 가구",
        sleepTime: "수면 시간 (11:59 PM - 7:00 AM)",
        fullDay: "하루 종일 (24시간)"
    },
    hi: {
        title: "एसी टनेज कैलकुलेटर",
        roomDimensions: "कमरे का आकार",
        length: "लंबाई",
        width: "चौड़ाई",
        height: "ऊंचाई",
        floor: "मंजिल",
        windows: "खिड़कियां और दरवाजे",
        numWindows: "खिड़कियों की संख्या",
        numDoors: "दरवाजों की संख्या",
        sunExposure: "धूप का प्रभाव",
        roomDetails: "कमरे का विवरण",
        insulation: "इन्सुलेशन प्रकार",
        occupants: "व्यक्तियों की संख्या",
        furniture: "फर्नीचर प्रकार",
        tempSettings: "तापमान सेटिंग",
        targetTemp: "लक्षित तापमान",
        usagePeriod: "उपयोग अवधि",
        calculate: "लोड की गणना करें",
        results: "परिणाम",
        currency: "रुपया",
        selectFloor: "मंजिल का चयन करें",
        groundFloor: "भूतल",
        middleFloor: "मध्य मंजिल",
        topFloor: "शीर्ष मंजिल",
        noSun: "कोई सीधी धूप नहीं",
        morningSun: "सुबह की धूप",
        afternoonSun: "दोपहर की धूप",
        allDaySun: "पूरे दिन की धूप",
        poorInsulation: "खराब इन्सुलेशन",
        averageInsulation: "औसत इन्सुलेशन",
        goodInsulation: "अच्छा इन्सुलेशन",
        minimalFurniture: "न्यूनतम फर्नीचर",
        woodenFurniture: "लकड़ी का फर्नीचर",
        metalFurniture: "धातु का फर्नीचर",
        mixedFurniture: "मिश्रित फर्नीचर",
        sleepTime: "सोने का समय (11:59 PM - 7:00 AM)",
        fullDay: "पूरा दिन (24 घंटे)"
    }
    // Add more languages as needed
};

const CURRENCY_SETTINGS = {
    US: { code: 'USD', symbol: '$', rate: 1 },
    EG: { code: 'EGP', symbol: 'ج.م', rate: 31.25 }, // 1 USD = 31.25 EGP
    UK: { code: 'GBP', symbol: '£', rate: 0.79 },
    EU: { code: 'EUR', symbol: '€', rate: 0.92 },
    // Add more currencies as needed
};
